#!/usr/bin/python

from .settings import Tables 


create_raw_table_sql = '''create table if not exists %s(receiveInfoId int not null primary key auto_increment, uuid varchar(50) character set utf8 collate utf8_bin, sourceType varchar(20) character set utf8 collate utf8_bin, email varchar(100) character set utf8 collate utf8_bin, arrivalTime varchar(30) character set utf8 collate utf8_bin, receiveType varchar(10) character set utf8 collate utf8_bin, receiveTime timestamp, receiveTitle TEXT, receiveContent MEDIUMTEXT, analysisFlg varchar(10) character set utf8 collate utf8_bin) engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin''' % (Tables["receive_table"])
 
create_analysis_table_sql = '''create table if not exists %s(reqanalysisId int not null primary key auto_increment, receiveInfoId int not null, mailCustomerName VARCHAR(60) character set utf8 collate utf8_bin, email varchar(100) character set utf8 collate utf8_bin, repCustName VARCHAR(60) character set utf8 collate utf8_bin, mailMonitorName varchar(60) character set utf8 collate utf8_bin, mailMonitorVersion varchar(60) character set utf8 collate utf8_bin, identityCode varchar(50) character set utf8 collate utf8_bin, kpiAssortment varchar(100) character set utf8 collate utf8_bin, kpiName varchar(60) character set utf8 collate utf8_bin, kpiValue varchar(100) character set utf8 collate utf8_bin, mailAlertContent MEDIUMTEXT, reqAlertContent MEDIUMTEXT, mailIp varchar(130) character set utf8 collate utf8_bin, reqAlertLevel varchar(5) character set utf8 collate utf8_bin, reqAlertTitle TEXT, reqAlertFrom varchar(60) character set utf8 collate utf8_bin, alertTime varchar(30) character set utf8 collate utf8_bin, repDeviceName varchar(30) character set utf8 collate utf8_bin, reqBadParts varchar(30) character set utf8 collate utf8_bin, repCity varchar(11) character set utf8 collate utf8_bin, mailCity varchar(100) character set utf8 collate utf8_bin, repCustId varchar(11) character set utf8 collate utf8_bin, repProjectName varchar(60) character set utf8 collate utf8_bin, repProjectId varchar(11) character set utf8 collate utf8_bin, serviceObject varchar(60) character set utf8 collate utf8_bin, serviceName varchar(100) character set utf8 collate utf8_bin, mailFactoryName varchar(20) character set utf8 collate utf8_bin,repFactoryName varchar(20) character set utf8 collate utf8_bin, mailModelName varchar(60) character set utf8 collate utf8_bin, repModelName varchar(60) character set utf8 collate utf8_bin, mailSn varchar(30) character set utf8 collate utf8_bin, repSn varchar(30) character set utf8 collate utf8_bin, businessSystem varchar(30) character set utf8 collate utf8_bin, maDept varchar(20) character set utf8 collate utf8_bin, maUser varchar(10) character set utf8 collate utf8_bin, maMobile varchar(20) character set utf8 collate utf8_bin, maEmail varchar(60) character set utf8 collate utf8_bin, analysisedTime varchar(30) character set utf8 collate utf8_bin, autoCreateFlg varchar(10) character set utf8 collate utf8_bin, inServiceFlg varchar(10) character set utf8 collate utf8_bin, dealStatus varchar(10) character set utf8 collate utf8_bin, createOn timestamp, modifiedOn timestamp DEFAULT CURRENT_TIMESTAMP) engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin''' % (Tables["format_table"]) 
# create_customer_system_table_sql = '''create table if not exists %s(id int not null primary key auto_increment, cust_system_code VARCHAR(60) character set utf8 collate utf8_bin, customer_code VARCHAR(60) character set utf8 collate utf8_bin, customer_name VARCHAR(60) character set utf8 collate utf8_bin, monitor_code varchar(60) character set utf8 collate utf8_bin, monitor_name varchar(60) character set utf8 collate utf8_bin, monitor_version varchar(60) character set utf8 collate utf8_bin, address varchar(100) character set utf8 collate utf8_bin, parameter varchar(100) character set utf8 collate utf8_bin, remark varchar(500) character set utf8 collate utf8_bin, active_flg varchar(10) character set utf8 collate utf8_bin, create_by varchar(10) character set utf8 collate utf8_bin, create_on timestamp, modified_by varchar(10) character set utf8 collate utf8_bin, modified_on timestamp DEFAULT CURRENT_TIMESTAMP) engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin''' % (Tables["customer_system_table"])
# 
# create_rule_table_sql = '''create table if not exists %s(rule_id int not null primary key auto_increment, cust_system_code VARCHAR(60) character set utf8 collate utf8_bin, rule_name varchar(30) character set utf8 collate utf8_bin, kpi_criterionalert MEDIUMTEXT, active_flg varchar(10) character set utf8 collate utf8_bin, create_by varchar(10) character set utf8 collate utf8_bin, create_on timestamp, modified_by varchar(10) character set utf8 collate utf8_bin, modified_on timestamp DEFAULT CURRENT_TIMESTAMP) engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin''' % (Tables["customer_alert_rule"])
# 
# create_case_matched_table_sql = '''create table if not exists %s(id int not null primary key auto_increment, info_id VARCHAR(10) character set utf8 collate utf8_bin, rule_name varchar(30) character set utf8 collate utf8_bin, rule_matched TEXT, kpis_and_content MEDIUMTEXT, deal_status varchar(10) character set utf8 collate utf8_bin, same_rule TEXT, created_on timestamp) engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin''' % (Tables["case_matched_rule"])
